.\"                                      MPS-YOUTUBE manpage
.\" (C) Copyright 2014 Zlatan Todoric <zlatan.todoric@gmail.com>,

.TH mps-youtube 1 "April 14, 2014" "mps-youtube manpage"

.SH NAME
mps-youtube \- Terminal based YouTube jukebox with playlist management

.SH DESCRIPTION
This manual page documents briefly the
.B mps-yotube
software which is based on mps, and uses YouTube as a source of content and can
play and download video as well as audio.

.B . or / <song|artist>
\-Searches  for song or artist

.B .. or // <song|artist>
\- Search in YouTube playlists

.B n|p
\-Next|Previous

.B d <number>
\-Downloads a song

.B all
\-Play all displayed tracks

.B vp 
\-to view the current playlist (then use rm, mv and sw to modify it)

.B ls 
\-to list your saved playlists

.B open <playlist_name or ID> 
\-to open a saved playlist as the current playlist

.B view <playlist_name or ID> 
\-to view a playlist (leaves current playlist intact)

.B play <playlist_name or ID> 
\-to play a saved playlist directly.

.B save or save <playlist_name> 
\-to save the currently displayed songs as a stored playlist on disk

.B rmp <playlist_name or ID> 
\-to delete a playlist from disk

.B mv <old_name or ID> <new_name> 
\-to rename a playlist

.B q 
\-to quit

.B h 
\-for help

.B top show 
\-top tracks this week

.SH EXAMPLES

Here are shown some additional examples for using mpsyt such as:

.B i 3
\-view info on item 3

.B d 3
\-to download item 3 (will open new menu)

.B da 3-5, 7
\-to download audio streams of items 3, 4, 5 and 7

.B dv 3-5, 7
\-to download video streams of items 3, 4, 5 and 7

.B u 3
\-to view more videos from uploader of item 3

.B r 3
\-to view videos related to item 3

.B da <number

.B 1,2,3 
\-to play songs 1 2 and 3

.B 2-4,6,6-3 
\-to play songs 2, 3, 4, 6, 6, 5, 4, 3

Note: The commands shuffle and repeat can be inserted at the start or end of any of the above to enable those play modes: eg, shuffle 1-4 or 2-4,1 repeat

.B rm 1,5
\-to remove songs 1 and 5
	
.B rm 1,2,5-7 
\-to remove songs 1,2 and 5-7

.B rm all 
\-to remove all songs

.B sw 1,3 
\-to swap the position of songs 1 and 3

.B mv 1,3 
\-to move song 1 to postion 3

.B add 1,2,3 
\-to add songs 1,2 and 3 to the current playlist.

.B add 1-4,6,8-10 
\-to add songs 1-4, 6, and 8-10 to the current playlist

.B add 1-4,7 <playlist_name> 
\-to add songs 1-4 and 7 to a saved playlist. A new playlist will be created if the given name doesn't already exist.

.B top3m 
\-show top tracks for last 3 months

.B top6m 
\-show top tracks for last 6 months

.B topyear 
\-show top tracks for last year

.B topall 
\-show all time top tracks

.SH AUTHOR
This manpage was created by Zlatan Todoric for use on Debian systems but can
be used on other as well.
